config/routes.rb
Rails.application.routes.draw do
  resources :insights, only: %i(index new create)
  root to: redirect { Rails.application.routes.url_helpers.insights_path }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insight.rb
class Insight < ApplicationRecord
  validates :body, presence: true, length: 1..1000
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/insights_controller.rb
class InsightsController < ApplicationController
  #http_basic_authenticate_with name: ENV.fetch("USER"), password: ENV.fetch("PASS"), except: %i(new create thanks)

  def index
    set_insights
    @new_insight = Insight.new
  end

  def new
    @insight = Insight.new
  end

  def thanks
  end

  def create
    set_insights
    @new_insight = Insight.new(insight_params)

    respond_to do |format|
      if @new_insight.save
        format.html { redirect_to insights_path, notice: "Insight salvo! Insight saved!" }
        format.json { render :show, status: :created, location: @new_insight }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @new_insight.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @insight = Insight.find(params[:id])
    @insight.destroy
    respond_to do |format|
      format.html { redirect_to insights_url, notice: "Insight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_insights
    @insights = Insight.all.order(id: :desc)
  end

  def insight_params
    params.require(:insight).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/views/insights/_form.html.erb
<%= form_with(model: insight) do |form| %>
  <% if insight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insight.errors.count, "error") %> prohibited this insight from being saved:</h2>

      <ul>
        <% insight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body do %>
      Please enter your insight
    <% end %>
    <%= form.text_area :body, rows: 5, cols: 30 %>
  </div>

  <div class="actions">
    <%= form.submit value: "Submit Insight!" %>
  </div>
<% end %>

app/views/insights/edit.html.erb
<h1>Editing Insight</h1>

<%= render 'form', insight: @insight %>

<%= link_to 'Show', @insight %> |
<%= link_to 'Back', insights_path %>

app/views/insights/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="item">
    <%= render 'form', insight: @new_insight %>
  </div>
  <% @insights.each do |insight| %>
    <div class="item">
      <pre><%= insight.body %></pre>
    </div>
  <% end %>
</div>

app/views/insights/new.html.erb
<%= render 'form', insight: @insight %>

app/views/insights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @insight.body %>
</p>

<%= link_to 'Edit', edit_insight_path(@insight) %> |
<%= link_to 'Back', insights_path %>

app/views/insights/thanks.html.erb
<h1>Thank you for the insight!</h1>

<%= link_to "Submit another insight!", new_insight_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puta Insight</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Puta Insight</h1>
    <hr>
    <%= yield %>
  </body>
</html>